spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    password: examplecompanies
    url: jdbc:postgresql://localhost:5432/companies
    username: usercompanies